### ISSUE TITLE
Ring BridgeERRORError: Cannot get schema for 'EcDsaSignature' target at AsnSchemaStorage.get

### ISSUE THREAD

**Issue by sahotanick** [dgreif/ring#1108]
# Bug Report

### Describe the Bug
When receiving a notification or clicking the doorbell in HomeKit I get the message "This camera is not responding", I do get notifications at the correct time when sensing motion or a doorbell press however the view of the doorbell always fails in HomeKit. The reason I feel this is not related to Live Streaming is because I do see the messages in the log: 

Preparing Live Stream for Front Door
Stream Prepared for Front Door (0.716s)
Activating stream for Front Door (0.831s)

### To Reproduce
 - Click on a notification received from doorbell
 - Error
OR
 - Click on doorbell view within HomeKit app
 - Error

### Expected behavior
When clicking on a notification or clicking on the doorbell view within HomeKit I expect the live stream to activate and present.

### Screenshots/Logs
![IMG_2434](https://user-images.githubusercontent.com/25302199/203039239-3ea3336d-0c79-400a-9384-ff59aa395c87.jpeg)

```
21/11/2022, 11:03:16Ring BridgeERRORError: Cannot get schema for 'EcDsaSignature' target
    at AsnSchemaStorage.get (/var/lib/hoobs/ringbridge/node_modules/@peculiar/webcrypto/node_modules/@peculiar/asn1-schema/build/cjs/schema.js:18:19)
    at Function.fromASN (/var/lib/hoobs/ringbridge/node_modules/@peculiar/webcrypto/node_modules/@peculiar/asn1-schema/build/cjs/parser.js:26:52)
    at Function.parse (/var/lib/hoobs/ringbridge/node_modules/@peculiar/webcrypto/node_modules/@peculiar/asn1-schema/build/cjs/parser.js:16:26)
    at Function.sign (/var/lib/hoobs/ringbridge/node_modules/@peculiar/webcrypto/build/webcrypto.js:1580:50)
    at EcdsaProvider.onSign (/var/lib/hoobs/ringbridge/node_modules/@peculiar/webcrypto/build/webcrypto.js:1740:25)
    at EcdsaProvider.sign (/var/lib/hoobs/ringbridge/node_modules/webcrypto-core/build/webcrypto-core.js:160:28)
    at SubtleCrypto.sign (/var/lib/hoobs/ringbridge/node_modules/webcrypto-core/build/webcrypto-core.js:1405:39)
    at Function.create (/var/lib/hoobs/ringbridge/node_modules/@peculiar/x509/build/x509.cjs.js:1815:35)
    at Function.CipherContext.createSelfSignedCertificateWithKey (/var/lib/hoobs/ringbridge/node_modules/dtls/src/context/cipher.ts:108:18)
    at RTCDtlsTransport.setupCertificate (/var/lib/hoobs/ringbridge/node_modules/werift/src/transport/dtls.ts:73:9)
    at ensureCert (/var/lib/hoobs/ringbridge/node_modules/werift/src/peerConnection.ts:1251:34)
    at RTCPeerConnection.ensureCerts (/var/lib/hoobs/ringbridge/node_modules/werift/src/peerConnection.ts:1259:7)
    at RTCPeerConnection.createAnswer (/var/lib/hoobs/ringbridge/node_modules/werift/src/peerConnection.ts:1264:5)
    at WeriftPeerConnection.createAnswer (/var/lib/hoobs/ringbridge/node_modules/ring-client-api/lib/streaming/peer-connection.js:117:24)
    at WebrtcConnection.handleMessage (/var/lib/hoobs/ringbridge/node_modules/ring-client-api/lib/streaming/webrtc-connection.js:29:32)
21/11/2022, 11:03:17Ring BridgeRingStopped Live Stream for Front Door
21/11/2022, 11:03:17Ring BridgeRingconnectionStateChange: closed
21/11/2022, 11:03:17Ring BridgeRingiceConnectionStateChange: closed
21/11/2022, 11:03:17Ring BridgeRingCall ended before answered

```
### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```
{
    "debug": true,
    "hideUnsupportedServices": true,
    "hideInHomeDoorbellSwitch": true,
    "hideAlarmSirenSwitch": true,
    "hideCameraSirenSwitch": true,
    "refreshToken": "XXXXXXXX",
    "hideCameraLight": true,
    "hideCameraMotionSensor": false,
    "hideLightGroups": true,
    "platform": "Ring"
}
```

### Environment

 - OS: Raspbian
 - Node.js: v16.16.0
 - NPM: 8.11.0
 - homebridge-ring: 11.6.0
 - homebridge: 1.5.0
 - hoobs: 4.2.8

**Comment by sahotanick** [comment]
@dgreif help would be much appreciated.

**Comment by dgreif** [comment]
I think this is probably related to https://github.com/PeculiarVentures/webcrypto/issues/50, but this is a sub dependency I'm not familiar with. Let's keep an eye on that issue and see if it gets fixed soon

**Comment by aficustree** [comment]
no longer able to start plugin

```
[1/15/2023, 2:35:53 AM] ====================
[1/15/2023, 2:35:53 AM] ERROR LOADING PLUGIN homebridge-ring:
[1/15/2023, 2:35:53 AM] Error: Cannot find module '@peculiar/asn1-schema'
Require stack:
- /homebridge/node_modules/homebridge-ring/node_modules/webcrypto-core/build/webcrypto-core.js
- /homebridge/node_modules/homebridge-ring/node_modules/werift/node_modules/@peculiar/webcrypto/build/webcrypto.js
- /homebridge/node_modules/homebridge-ring/node_modules/werift/lib/dtls/src/context/cipher.js
- /homebridge/node_modules/homebridge-ring/node_modules/werift/lib/webrtc/src/utils.js
- /homebridge/node_modules/homebridge-ring/node_modules/werift/lib/webrtc/src/media/rtpReceiver.js
- /homebridge/node_modules/homebridge-ring/node_modules/werift/lib/webrtc/src/media/router.js
- /homebridge/node_modules/homebridge-ring/node_modules/werift/lib/webrtc/src/peerConnection.js
- /homebridge/node_modules/homebridge-ring/node_modules/werift/lib/webrtc/src/index.js
- /homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/peer-connection.js
- /homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/streaming-connection-base.js
- /homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/webrtc-connection.js
- /homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/ring-camera.js
- /homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/location.js
- /homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/api.js
- /homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/index.js
- /homebridge/node_modules/homebridge-ring/lib/ring-platform.js
- /homebridge/node_modules/homebridge-ring/lib/index.js
- /homebridge/node_modules/homebridge/lib/plugin.js
- /homebridge/node_modules/homebridge/lib/pluginManager.js
- /homebridge/node_modules/homebridge/lib/server.js
- /homebridge/node_modules/homebridge/lib/cli.js
- /homebridge/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-ring/node_modules/webcrypto-core/build/webcrypto-core.js:10:18)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
[1/15/2023, 2:35:53 AM] ====================
```

**Comment by NickRivait** [comment]
How do I fix it then? This is 3 months old.

**Comment by dgreif** [comment]
I don't have a fix at this point. I suggest you reach out to HOOBS support and request they look into it as this appears to be HOOBS specific.

**Comment by NickRivait** [comment]
From Hoobs

Response to ticket "6400-9D87-00B9-A9CE-602A-0013".

Hello,

This seems to be caused due to the recent update that the plugin developer did on Feb 25, 2023
I too have had the same issue and I went into the plugin page on HOOBS™ and clicked on the ring plugin and then click versions (its under the orange configuration button)
From there I downloaded the 11.7.1 version and was able to login and after scanning with apple home was able to get the live view again.

If you have any questions it's OK to reply to this email, and your ticket will be updated.

Thank You,
HOOBS Support Team

**Comment by cantchooseaname8** [comment]
Just reporting that I get the same error after the last update and can no longer access live video from the cameras.

**Comment by jpbertram** [comment]
Just updated to 11.7.2 and am experiencing the same issue. Downgrading back to 11.7.1, which was previously working prior to the update, now also throws the error. Thumbnails update in HomeKit, but stream will not activate.

**Comment by silverfox3058** [comment]
@dgreif  I’m having exactly the same issue as @jpbertram & @NickRivait.  

04/03/2023, 20:58:08Ring BridgeRingPreparing Live Stream for Front Drive
04/03/2023, 20:58:08Ring BridgeRingStream Prepared for Front Drive (0.647s)
04/03/2023, 20:58:09Ring BridgeRingActivating stream for Front Drive (0.964s)
04/03/2023, 20:58:09Ring BridgeRingiceConnectionStateChange: completed
04/03/2023, 20:58:09Ring BridgeERRORError: Cannot get schema for 'EcDsaSignature' target
    at AsnSchemaStorage.get (/var/lib/hoobs/ringbridge/node_modules/@peculiar/asn1-schema/build/cjs/schema.js:17:19)
    at Function.fromASN (/var/lib/hoobs/ringbridge/node_modules/@peculiar/asn1-schema/build/cjs/parser.js:26:52)
    at Function.parse (/var/lib/hoobs/ringbridge/node_modules/@peculiar/asn1-schema/build/cjs/parser.js:16:26)
    at Function.sign (/var/lib/hoobs/ringbridge/node_modules/@peculiar/webcrypto/build/webcrypto.js:1574:50)
    at EcdsaProvider.onSign (/var/lib/hoobs/ringbridge/node_modules/@peculiar/webcrypto/build/webcrypto.js:1737:25)
    at EcdsaProvider.sign (/var/lib/hoobs/ringbridge/node_modules/webcrypto-core/build/webcrypto-core.js:160:28)
    at SubtleCrypto.sign (/var/lib/hoobs/ringbridge/node_modules/webcrypto-core/build/webcrypto-core.js:1405:39)
    at Function.create (/var/lib/hoobs/ringbridge/node_modules/@peculiar/x509/build/x509.cjs.js:2407:35)
    at Function.CipherContext.createSelfSignedCertificateWithKey (/var/lib/hoobs/ringbridge/node_modules/dtls/src/context/cipher.ts:108:18)
    at RTCDtlsTransport.setupCertificate (/var/lib/hoobs/ringbridge/node_modules/werift/src/transport/dtls.ts:73:9)
    at ensureCert (/var/lib/hoobs/ringbridge/node_modules/werift/src/peerConnection.ts:1289:34)
    at RTCPeerConnection.ensureCerts (/var/lib/hoobs/ringbridge/node_modules/werift/src/peerConnection.ts:1297:7)
    at RTCPeerConnection.createAnswer (/var/lib/hoobs/ringbridge/node_modules/werift/src/peerConnection.ts:1302:5)
    at WeriftPeerConnection.createAnswer (/var/lib/hoobs/ringbridge/node_modules/ring-client-api/lib/streaming/peer-connection.js:117:24)
    at WebrtcConnection.handleMessage (/var/lib/hoobs/ringbridge/node_modules/ring-client-api/lib/streaming/webrtc-connection.js:29:32)
04/03/2023, 20:58:09Ring BridgeRingStopped Live Stream for Front Drive
04/03/2023, 20:58:09Ring BridgeRingconnectionStateChange: closed
04/03/2023, 20:58:09Ring BridgeRingiceConnectionStateChange: closed

**Comment by NickRivait** [comment]
I did the full backup, restore etc. 

Made it worse. See attached. 

![image](https://user-images.githubusercontent.com/75817378/222974669-37dedd9d-f7f5-41c2-b426-803fad78c900.png)

**Comment by prausch** [comment]
I'm using this bridge with HOOBS, and uninstalling the 11.7.2 and reinstalling (into the same bridge) the 11.7.1 version worked to resolve this error.

**Comment by NickRivait** [comment]
Did you have to redo all your ring sfuff? Thank you,Nick ***@***.*** Mar 5, 2023, at 1:54 PM, prausch ***@***.***> wrote:﻿
I'm using this bridge with HOOBS, and uninstalling the 11.7.2 and reinstalling (into the same bridge) the 11.7.1 version worked to resolve this error.

**Comment by prausch** [comment]
> Did you have to redo all your ring sfuff? Thank you,Nick

No, but I think preserving the bridge ID and location ID are necessary.

I copied my location ID, then uninstalled, but left the HOOBS bridge (didn't check the "Remove empty bridge" option). My Ring devices disappeared from HomeKit.

Ithen reinstalled to the same bridge (selected the old Ring HOOBS bridge in the bottom section). I pasted my location back into the configuration, and relinked my Ring account. Then HomeKit saw the devices, and they came back into the same rooms and the cameras were working.

**Comment by prausch** [comment]
Looks like the issue is that in v11.7.2, the stream open was wrapped with an error check, and the stream open was probably always throwing an error, but still working. The error check now returns without supplying the stream.

At line 619 of camera-source.ts:
`      await session.activate(request)`
is replaced with:
`      try {
        await session.activate(request)
      } catch (e) {
        logError('Failed to activate stream')
        logError(e)
        callback(new Error('Failed to activate stream'))

        return
      }`

**Comment by dgreif** [comment]
I dug into this some more today, and I've still been unable to recreate or track down the cause of this issue. I'm fairly certain that everyone having issues with `EcDsaSignature` is on HOOBS (let me know if you are not). I'd recommend making sure you are on the latest version of HOOBS, and ideally updating to Node 18 if you haven't already.

I also pushed some changes in v11.7.3 which require the latest version of the dependencies where this error is popping up. I can't guarantee this will fix anything, but figured it was worth a try. Can you try the latest version and see if it works now?

**Comment by NickRivait** [comment]
This seems to have fixed mine.

**Comment by cantchooseaname8** [comment]
I can stream live camera feed now without the error. However, the video is very slow and choppy and will freeze. It works fine within the actual Ring app, so I'm not sure why the connection isn't as good with the homebridge plugin

**Comment by silverfox3058** [comment]
Still getting the error. I’m on HOOBS 4.3.0 & Node 16.19.1

**Comment by prausch** [comment]
I'm also still receiving the error on all Ring cameras (5) with HOOBS 4.3.0 (Intel Debian), node 16.19.1, Homebridge 1.6.0.

Log looks like this for all cameras, with the differences between cameras being the reported prep and activation times and the names of the cameras.

3/27/2023, 8:32:54 AMRing BridgeRingPreparing Live Stream for West Side
3/27/2023, 8:32:55 AMRing BridgeRingStream Prepared for West Side (0.5s)
3/27/2023, 8:32:55 AMRing BridgeRingActivating stream for West Side (0.579s)
3/27/2023, 8:32:55 AMRing BridgeRingiceConnectionStateChange: completed
3/27/2023, 8:32:55 AMRing BridgeRingERRORError: Cannot get schema for 'EcDsaSignature' target
3/27/2023, 8:32:55 AMRing BridgeRingconnectionStateChange: closed
3/27/2023, 8:32:55 AMRing BridgeRingiceConnectionStateChange: closed
3/27/2023, 8:32:55 AMRing BridgeRingERRORFailed to activate stream
3/27/2023, 8:32:55 AMRing BridgeRingERRORError: Cannot get schema for 'EcDsaSignature' target

**Comment by dgreif** [comment]
@silverfox3058 @prausch can you try updating to node 18 and see if that helps?

**Comment by prausch** [comment]
There's no method to update specific Debian packages in the Hoobs interface. I think they were pretty proud of updating to node v16 ("updated dependencies!") when they released version 4.3.0 of hoobs. Seems like 16.19.1 is the version that comes with the LTS Debian (5.10.136-1) being used by Hoobs.

Any reference on how to safely update ? I've found [some ancient (2020) snippet](https://www.reddit.com/r/HOOBS/comments/k573ui/node_update/) on how to wget and bind node and hoobs, but it looks pretty arcane, and like it's going to reinstall hoobs completely.

wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts && sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node

That installed the current version (16.19.1), and had some errors, so I restored the snapshot. Seems like it would have the same errors if I specified a different node version, and maybe the hoobsians would have used a newer node version if they could?

**Comment by connorrichlen** [comment]
> There's no method to update specific Debian packages in the Hoobs interface. I think they were pretty proud of updating to node v16 ("updated dependencies!") when they released version 4.3.0 of hoobs. Seems like 16.19.1 is the version that comes with the LTS Debian (5.10.136-1) being used by Hoobs.
> 
> Any reference on how to safely update ? I've found [some ancient (2020) snippet](https://www.reddit.com/r/HOOBS/comments/k573ui/node_update/) on how to wget and bind node and hoobs, but it looks pretty arcane, and like it's going to reinstall hoobs completely.
> 
> wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts && sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node
> 
> That installed the current version (16.19.1), and had some errors, so I restored the snapshot. Seems like it would have the same errors if I specified a different node version, and maybe the hoobsians would have used a newer node version if they could?

I saw somewhere on the web that this was a suggested fix, I cannot figure out how to on hoobs though. Tough. 

I’m getting the same error, 
`[4/3/23, 11:56 PM] [Ring Bridge] Preparing Live Stream for Front Door
[4/3/23, 11:56 PM] [Ring Bridge] Stream Prepared for Front Door (0.552s)
[4/3/23, 11:56 PM] [Ring Bridge] Activating stream for Front Door (0.683s)
[4/3/23, 11:56 PM] [Ring Bridge] iceConnectionStateChange: completed
[4/3/23, 11:56 PM] [Ring Bridge] [ERROR] Error: Cannot get schema for 'EcDsaSignature' target
[4/3/23, 11:56 PM] [Ring Bridge] connectionStateChange: closed
[4/3/23, 11:56 PM] [Ring Bridge] iceConnectionStateChange: closed
[4/3/23, 11:56 PM] [Ring Bridge] [ERROR] Failed to activate stream
[4/3/23, 11:56 PM] [Ring Bridge] [ERROR] Error: Cannot get schema for 'EcDsaSignature' target
[4/3/23, 11:56 PM] [Ring Bridge] Preparing Live Stream for Living Room
[4/3/23, 11:56 PM] [Ring Bridge] Stream Prepared for Living Room (0.72s)
[4/3/23, 11:56 PM] [Ring Bridge] Activating stream for Living Room (0.789s)
[4/3/23, 11:56 PM] [Ring Bridge] iceConnectionStateChange: completed
[4/3/23, 11:56 PM] [Ring Bridge] [ERROR] Error: Cannot get schema for 'EcDsaSignature' target
[4/3/23, 11:56 PM] [Ring Bridge] connectionStateChange: closed
[4/3/23, 11:56 PM] [Ring Bridge] iceConnectionStateChange: closed
[4/3/23, 11:56 PM] [Ring Bridge] [ERROR] Failed to activate stream
[4/3/23, 11:56 PM] [Ring Bridge] [ERROR] Error: Cannot get schema for 'EcDsaSignature' target
`

**Comment by dgreif** [comment]
I'd suggest reaching out to HOOBS support and asking if there is a way to update Node.js

**Comment by prausch** [comment]
I used these instructions to install n for npm and and then update node.js. It worked. 

I made a backup and snapshot before I did these actions referenced in this article: https://www.hostingadvice.com/how-to/update-node-js-latest-version/

```
sudo npm install npm@latest -g  #install the most recent npm update.
npm -v  # to validate that the npm version was updated correctly.
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

Working with Ring homebridge plugin 11.7.4.

**Comment by silverfox3058** [comment]
Thanks @prausch for the instructions for updating to Node 18. I’m now on 18.15.0 however @dgreif the same error occurs

18:55:10Ring BridgeRingERRORFailed to activate stream
18:55:10Ring BridgeRingERRORError: Cannot get schema for 'EcDsaSignature' target

**Comment by prausch** [comment]
Did you empty the hoobs caches, and install the plugin into the same bridge as the old one? I am not having the error any longer, but did when I accidentally installed the plugin to a NEW bridge in Hoobs.

It's possible that you may need to delete the Ring bridge, empty the caches and install the 11.7.4 Ring plugin into a new bridge. You will have to add back all of your Ring devices to Home though.

**Comment by silverfox3058** [comment]
Hi @prausch thanks for the additional instructions. All done & now working

**Comment by dgreif** [comment]
Thanks for the extra tip on clearing HOOBS cache @prausch. Is there an article somewhere that describes how to do that?

I'm going to close this issue as the problem appears to be resolved for most users.

**Comment by prausch** [comment]
I don't see where the cache clearing process is documented. I'm not certain it's necessary, but does seem relevant. One clears the cache by going to the bridges (http://[hoobs IP or hoobs.local]/bridges), click the Ring bridge (or bridge requiring cache clearing), click the Cache button, click the Clear button.

I think the key for this repair is to install the update into the existing bridge that the Ring plugin was installed into before. The default is to create a new bridge for the installation, even though you've selected the update from list.

**Comment by BinDevID** [comment]
Same here. On Hoobs. Get Cannot get schema for 'EcDsaSignature' target. Broke ring streaming.

**Comment by prausch** [comment]
> Same here. On Hoobs. Cannot get schema for 'EcDsaSignature' target. Broke ring streaming.
> 
> Tried Hoobs App / Bridges / (Bridge) / Cache / Clear
> 
> This required me to add the bridge back into the home app (a pain), and it still didn't fix the error and ring streams still don't work. So not sure going through the clear cache will help.

Did you see the instructions above to install n for npm and use that to upgrade node to the version expected by Ring Bridge? Also note that you need to install the update to your existing bridge (not a new bridge) in Hoobs after the node upgrade.

**Comment by BinDevID** [comment]
Was able to resolve this using previous suggestion.

Tried Hoobs App / Bridges / (Bridge) / Cache / Clear (this didn't work)
Uninstalled Ring Plugin

Through Windows Terminal, connected and ran:

```
sudo npm install npm@latest -g  #install the most recent npm update.
npm -v  # to validate that the npm version was updated correctly.
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

Reinstalled the Ring Plugin.
This fixed it.

I am not sure if it was the updates or the uninstall/reinstall of plugin or cache clearing, but it is working properly now.
