### ISSUE TITLE
Updated to latest version and doesn't work 9.18.5 and get 404 error connecting to API

### ISSUE THREAD

**Issue by alangsam1** [dgreif/ring#702]
# Bug Report

### Describe the Bug
 updated Ring Plugin to latest 9.18.5. and rebooted.Immediately got errors. Uninstalled and reinstalled on a separate RING Bridge and still doesn't work.

### To Reproduce
 - Start Homebridge
 - Attempt to start/ All other plugins load.
 then Ring doesn't open 

 - 7/27/2021, 2:49:47 PMRing BridgeRingERRORRequest to https://app.ring.com/rhq/v1/devices/v1/locations failed with status 404. Response body: 
7/27/2021, 2:49:47 PMRing BridgeRingERRORError connecting to API
7/27/2021, 2:49:47 PMRing BridgeRingERRORHTTPError: Response code 404 (Not Found)

### Expected behavior

 expected to see my camera images in the homekit addable to stream etc. 

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A7/27/2021, 2:33:38 PMHOOBSRingConfiguring cached accessory f2878488-b3bd-4d62-8dec-09ef10b43932 Front Door
7/27/2021, 2:33:38 PMHOOBSRingConfiguring cached accessory b74668e3-8a43-41cc-8128-0d4943a6a258 Oceanside
7/27/2021, 2:33:38 PMHOOBSRingConfiguring cached accessory 9a817284-b4a5-4328-87b7-f50e4a4b5ca0 North Side 
7/27/2021, 2:33:38 PMHOOBSRingConfiguring cached accessory 4ba2ba7b-cb9e-4fc3-8d29-53a2e306d89c Side
7/27/2021, 2:33:38 PMHOOBSRingConfiguring cached accessory 802bf8e3-cf88-4408-a8f3-ec8c897433c1 Garage
7/27/2021, 2:33:38 PMHOOBSRingConfiguring cached accessory c1c1f459-87bd-4868-af25-a4248d6455b5 Downstairs
7/27/2021, 2:33:38 PMHOOBSRingConfiguring cached accessory cbcec25d-8060-45e6-93c2-3c2f88ac69e6 Upstairs
7/27/2021, 2:33:38 PMHOOBSRingConfiguring cached accessory 6ab27d07-b337-4648-8752-b537cf7d43ef Upstairs
7/27/2021, 2:33:38 PMHOOBSScreenLogicdiscoverDevices
7/27/2021, 2:33:38 PMHOOBSTccdidFinishLaunching
7/27/2021, 2:33:38 PMHOOBSBridge is running on port 51826.
7/27/2021, 2:33:38 PMHOOBSScreenLogicdiscoverDevices connected: 08-38-A6 POOL: 5.2 Build 738.0 Rel
7/27/2021, 2:33:38 PMHOOBSScreenLogicRestoring existing accessory from cache: Pool
7/27/2021, 2:33:38 PMHOOBSScreenLogicRestoring existing accessory from cache: Air
7/27/2021, 2:33:38 PMHOOBSScreenLogicRestoring existing accessory from cache: Pool Heater
7/27/2021, 2:33:38 PMHOOBSScreenLogicRestoring existing accessory from cache: Aux 1
7/27/2021, 2:33:38 PMHOOBSScreenLogicRestoring existing accessory from cache: Aux 2
7/27/2021, 2:33:38 PMHOOBSScreenLogicRestoring existing accessory from cache: Aux 3
7/27/2021, 2:33:38 PMHOOBSScreenLogicRestoring existing accessory from cache: Pool
7/27/2021, 2:33:38 PMHOOBSScreenLogicRestoring existing accessory from cache: Feature 1
7/27/2021, 2:33:38 PMHOOBSScreenLogicRestoring existing accessory from cache: Feature 2
7/27/2021, 2:33:39 PMHOOBSTccExisting TCC accessory (deviceID=2673959) THERMOSTAT
7/27/2021, 2:33:39 PMHOOBSTccExisting TCC accessory (deviceID=3720817) PFVB DOWNSTAIR
7/27/2021, 2:33:39 PMHOOBSRingERRORRequest to https://app.ring.com/rhq/v1/devices/v1/locations failed with status 404. Response body: 
7/27/2021, 2:33:39 PMHOOBSRingERRORError connecting to API
7/27/2021, 2:33:39 PMHOOBSRingERRORHTTPError: Response code 404 (Not Found)
7/27/2021, 2:33:40 PMHOOBSRoombaRunning status requested
7/27/2021, 2:33:40 PMHOOBSRoombaBattery status requested
7/27/2021, 2:33:40 PMHOOBSRoombaBattery level requested
7/27/2021, 2:33:40 PMHOOBSRoombaCharging status requested
7/27/2021, 2:33:40 PMHOOBSRoombaDocked status requested
7/27/2021, 2:35:25 PMHOOBSConfiguration change
7/27/2021, 2:35:25 PMhoobs stopping
7/27/2021, 2:35:29 PMHOOBS starting
7/27/2021, 2:35:32 PMHOOBSLoaded plugin 'homebridge-fordpass'
7/27/2021, 2:35:33 PMHOOBSLoaded plugin 'homebridge-roomba2'
7/27/2021, 2:35:33 PMHOOBSLoaded plugin 'homebridge-screenlogic'
7/27/2021, 2:35:33 PMHOOBSLoaded plugin 'homebridge-tcc'
7/27/2021, 2:35:35 PMHOOBSLoading 3 platforms...
7/27/2021, 2:35:35 PMHOOBSLoading 1 accessories...
7/27/2021, 2:35:35 PMHOOBSRoombaEnabling keepAlive
7/27/2021, 2:35:35 PMHOOBSScreenLogicLoading accessory from cache: Pool
7/27/2021, 2:35:35 PMHOOBSScreenLogicLoading accessory from cache: Air
7/27/2021, 2:35:35 PMHOOBSScreenLogicLoading accessory from cache: Pool Heater
7/27/2021, 2:35:35 PMHOOBSScreenLogicLoading accessory from cache: Aux 1
7/27/2021, 2:35:35 PMHOOBSScreenLogicLoading accessory from cache: Aux 2
7/27/2021, 2:35:35 PMHOOBSScreenLogicLoading accessory from cache: Aux 3
7/27/2021, 2:35:35 PMHOOBSScreenLogicLoading accessory from cache: Pool
7/27/2021, 2:35:35 PMHOOBSScreenLogicLoading accessory from cache: Feature 1
7/27/2021, 2:35:35 PMHOOBSScreenLogicLoading accessory from cache: Feature 2
7/27/2021, 2:35:35 PMHOOBSFordPassConfiguring accessory Raptor
7/27/2021, 2:35:35 PMHOOBSTccconfigureAccessory THERMOSTAT
7/27/2021, 2:35:35 PMHOOBSTccconfigureAccessory PFVB DOWNSTAIR
7/27/2021, 2:35:35 PMHOOBSFailed to find plugin to handle accessory Back Door
7/27/2021, 2:35:35 PMHOOBSFailed to find plugin to handle accessory Upstairs back door
7/27/2021, 2:35:35 PMHOOBSFailed to find plugin to handle accessory Front Door
7/27/2021, 2:35:35 PMHOOBSFailed to find plugin to handle accessory Oceanside
7/27/2021, 2:35:35 PMHOOBSFailed to find plugin to handle accessory North Side 
7/27/2021, 2:35:35 PMHOOBSFailed to find plugin to handle accessory Side
7/27/2021, 2:35:35 PMHOOBSFailed to find plugin to handle accessory Garage
7/27/2021, 2:35:35 PMHOOBSFailed to find plugin to handle accessory Downstairs
7/27/2021, 2:35:35 PMHOOBSFailed to find plugin to handle accessory Upstairs
7/27/2021, 2:35:35 PMHOOBSFailed to find plugin to handle accessory Upstairs
7/27/2021, 2:35:35 PMHOOBSScreenLogicdiscoverDevices
7/27/2021, 2:35:35 PMHOOBSTccdidFinishLaunching
7/27/2021, 2:35:35 PMHOOBSBridge is running on port 51826.
7/27/2021, 2:35:35 PMHOOBSScreenLogicdiscoverDevices connected: 08-38-A6 POOL: 5.2 Build 738.0 Rel
7/27/2021, 2:35:35 PMHOOBSScreenLogicRestoring existing accessory from cache: Pool
7/27/2021, 2:35:35 PMHOOBSScreenLogicRestoring existing accessory from cache: Air
7/27/2021, 2:35:35 PMHOOBSScreenLogicRestoring existing accessory from cache: Pool Heater
7/27/2021, 2:35:35 PMHOOBSScreenLogicRestoring existing accessory from cache: Aux 1
7/27/2021, 2:35:35 PMHOOBSScreenLogicRestoring existing accessory from cache: Aux 2
7/27/2021, 2:35:35 PMHOOBSScreenLogicRestoring existing accessory from cache: Aux 3
7/27/2021, 2:35:35 PMHOOBSScreenLogicRestoring existing accessory from cache: Pool
7/27/2021, 2:35:35 PMHOOBSScreenLogicRestoring existing accessory from cache: Feature 1
7/27/2021, 2:35:35 PMHOOBSScreenLogicRestoring existing accessory from cache: Feature 2
7/27/2021, 2:35:36 PMHOOBSTccExisting TCC accessory (deviceID=2673959) THERMOSTAT
7/27/2021, 2:35:36 PMHOOBSTccExisting TCC accessory (deviceID=3720817) PFVB DOWNSTAIR
7/27/2021, 2:35:37 PMHOOBSRoombaRunning status requested
7/27/2021, 2:35:37 PMHOOBSRoombaBattery status requested
7/27/2021, 2:35:37 PMHOOBSRoombaBattery level requested
7/27/2021, 2:35:37 PMHOOBSRoombaCharging status requested
7/27/2021, 2:35:37 PMHOOBSRoombaDocked status requested
7/27/2021, 2:36:03 PMRing Bridge starting
7/27/2021, 2:36:14 PMRing BridgeWARNINGNo plugins installed.
7/27/2021, 2:36:14 PMRing BridgeBridge is running on port 52826.
7/27/2021, 2:36:30 PMRing BridgeConfiguration change
7/27/2021, 2:36:30 PMringbridge stopping
7/27/2021, 2:36:35 PMRing Bridge starting
7/27/2021, 2:36:43 PMHOOBSRoombaRunning status requested
7/27/2021, 2:36:43 PMHOOBSRoombaBattery status requested
7/27/2021, 2:36:43 PMHOOBSRoombaBattery level requested
7/27/2021, 2:36:43 PMHOOBSRoombaCharging status requested
7/27/2021, 2:36:43 PMHOOBSRoombaDocked status requested
7/27/2021, 2:36:45 PMRing BridgeLoaded plugin 'homebridge-ring'
7/27/2021, 2:36:45 PMRing BridgeLoading 1 platforms...
7/27/2021, 2:36:45 PMRing BridgeRingERRORRequest to https://app.ring.com/rhq/v1/devices/v1/locations failed:
7/27/2021, 2:36:45 PMRing BridgeRingERRORError: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
7/27/2021, 2:36:45 PMRing BridgeRingERRORError connecting to API
7/27/2021, 2:36:45 PMRing BridgeRingERRORError: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
7/27/2021, 2:36:45 PMRing BridgeBridge is running on port 52826.
7/27/2021, 2:37:43 PMRing BridgeConfiguration change
7/27/2021, 2:37:43 PMringbridge stopping
7/27/2021, 2:37:47 PMRing Bridge starting
7/27/2021, 2:37:51 PMRing BridgeLoaded plugin 'homebridge-ring'
7/27/2021, 2:37:51 PMRing BridgeLoading 1 platforms...
7/27/2021, 2:37:51 PMRing BridgeBridge is running on port 52826.
7/27/2021, 2:37:52 PMRing BridgeRingERRORRequest to https://app.ring.com/rhq/v1/devices/v1/locations failed with status 404. Response body: 
7/27/2021, 2:37:52 PMRing BridgeRingERRORError connecting to API
7/27/2021, 2:37:52 PMRing BridgeRingERRORHTTPError: Response code 404 (Not Found)
7/27/2021, 2:43:36 PMHOOBSRoombaRunning status requested
7/27/2021, 2:43:36 PMHOOBSRoombaBattery status requested
7/27/2021, 2:43:36 PMHOOBSRoombaDocked status requested
7/27/2021, 2:43:38 PMHOOBSRoombaBattery status requested
7/27/2021, 2:45:19 PMHOOBSRoombaRunning status requested
7/27/2021, 2:45:19 PMHOOBSRoombaBattery status requested
7/27/2021, 2:45:19 PMHOOBSRoombaBattery level requested
7/27/2021, 2:45:19 PMHOOBSRoombaCharging status requested
7/27/2021, 2:45:19 PMHOOBSRoombaDocked status requested
7/27/2021, 2:45:21 PMHOOBSRoombaRunning status requested
7/27/2021, 2:45:21 PMHOOBSRoombaBattery status requested
7/27/2021, 2:45:21 PMHOOBSRoombaDocked status requested
7/27/2021, 2:45:35 PMHOOBSRoombaBattery status requested
7/27/2021, 2:46:27 PMHOOBSRoombaBattery status requested
7/27/2021, 2:47:19 PMHOOBSRoombaRunning status requested
7/27/2021, 2:47:19 PMHOOBSRoombaBattery status requested
7/27/2021, 2:47:19 PMHOOBSRoombaBattery level requested
7/27/2021, 2:47:19 PMHOOBSRoombaCharging status requested
7/27/2021, 2:47:19 PMHOOBSRoombaDocked status requested
7/27/2021, 2:47:29 PMHOOBSRoombaRunning status requested
7/27/2021, 2:47:29 PMHOOBSRoombaBattery status requested
7/27/2021, 2:47:29 PMHOOBSRoombaBattery level requested
7/27/2021, 2:47:29 PMHOOBSRoombaCharging status requested
7/27/2021, 2:47:29 PMHOOBSRoombaDocked status requested
7/27/2021, 2:47:35 PMHOOBSRoombaBattery status requested
7/27/2021, 2:48:29 PMHOOBSRoombaBattery status requested
7/27/2021, 2:49:32 PMHOOBSRoombaBattery status requested
7/27/2021, 2:49:38 PMringbridge stopping
7/27/2021, 2:49:42 PMRing Bridge starting
7/27/2021, 2:49:46 PMRing BridgeLoaded plugin 'homebridge-ring'
7/27/2021, 2:49:46 PMRing BridgeLoading 1 platforms...
7/27/2021, 2:49:46 PMRing BridgeBridge is running on port 52826.
7/27/2021, 2:49:46 PMHOOBSRoombaBattery status requested
7/27/2021, 2:49:47 PMRing BridgeRingERRORRequest to https://app.ring.com/rhq/v1/devices/v1/locations failed with status 404. Response body: 
7/27/2021, 2:49:47 PMRing BridgeRingERRORError connecting to API
7/27/2021, 2:49:47 PMRing BridgeRingERRORHTTPError: Response code 404 (Not Found)
7/27/2021, 2:49:51 PMHOOBSRoombaBattery status requested
7/27/2021, 2:50:25 PMHOOBSRoombaRunning status requested
7/27/2021, 2:50:25 PMHOOBSRoombaBattery status requested
7/27/2021, 2:50:25 PMHOOBSRoombaDocked status requested

**Comment by mikesalz** [comment]
Got the yuck here too...

> [7/27/2021, 7:17:55 PM] [Ring] Request to https://app.ring.com/rhq/v1/devices/v1/locations failed with status 404. Response body: 
> [7/27/2021, 7:17:55 PM] [Ring] Error connecting to API
> [7/27/2021, 7:17:55 PM] [Ring] HTTPError: Response code 404 (Not Found)
>     at Request.<anonymous> (/homebridge/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:117:42)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
>   code: undefined,
>   timings: {
>     start: 1627413475111,
>     socket: 1627413475344,
>     lookup: undefined,
>     connect: undefined,
>     secureConnect: undefined,
>     upload: 1627413475344,
>     response: 1627413475402,
>     end: 1627413475403,
>     error: undefined,
>     abort: undefined,
>     phases: {
>       wait: 233,
>       dns: undefined,
>       tcp: undefined,
>       tls: undefined,
>       request: NaN,
>       firstByte: 58,
>       download: 1,
>       total: 292
>     }
>   }
> }

**Comment by lishan89uc** [comment]
ehhh, downgrading to previous versions didn't work... HELP!

**Comment by mpreissner** [comment]
This is the same issue as described in #699

**Comment by gburlile** [comment]
Same issue here.

**Comment by searay345** [comment]
Same issue here. Using HOOBS 4.0.96 on a Pi4 and the latest ring plugin release. Node version 14.17.2. Homebridge version 1.3.4. Cameras are inaccessible from HomeKit and I can't change alarm status or do anything with Ring in HomeKit. Patiently awaiting a fix.

**Comment by nertwork** [comment]
Can confirm same issue - hopefully we can make le fix!

**Comment by rpmartinez3** [comment]
Same here.

**Comment by mjwillson23** [comment]
I have this same issue, though it seems to have just started occurring rather suddenly, I had previously updated this plugin yesterday and did not notice this same error originally.

**Comment by neameo** [comment]
Same issue but only after setting plugin to run as child bridge, had previously updated to latest version (9.18.5) without issue.

**Comment by lishan89uc** [comment]
I am starting to think its not the integration but rather amazon/ring turned off something.... to stop us from using methods like this to get homekit support. or maybe they just changed the url ROFL

**Comment by dgreif** [comment]
Looks like Ring removed the endpoint we were using before.  Fixed in `9.18.6`

**Comment by mikesalz** [comment]
@dgreif Homebridge tells me there is an update to the plugin.  When I run the update, it appears to be installing.  But I am still at homebridge-ring v9.18.5 when the update completes.  I have tried restarting Homebridge, and that doesn't help.  Thoughts?

**Comment by lishan89uc** [comment]
@dgreif i know you probably just haven't gotten around to it but the latest on npm is still 9.18.5 however it shows an update for 9.18.6 LOL

**Comment by searay345** [comment]
I think we just need to wait for it to propagate. HOOBS still doesn't show an available update yet.

**Comment by appler1d3r** [comment]
> I think we just need to wait for it to propagate. HOOBS still doesn't show an available update yet.

Updated around 12 PM AEST and was able to do successfully. The errors are gone now and Ring is back to stable mode.
Thank you!

**Comment by searay345** [comment]
> > I think we just need to wait for it to propagate. HOOBS still doesn't show an available update yet.
> 
> 
> 
> Updated around 12 PM AEST and was able to do successfully. The errors are gone now and Ring is back to stable mode.
> 
> @dgreif Thank you!

Yup, I updated around 11:45PM EST. HOOBS finally showed the update. It took about 3 hours for it to propagate through the HOOBS library. That's good to know for future reference. Thank you @dgreif the update is working great now.
